from __future__ import annotations

import uuid
from typing import Any, Protocol

from control_plane.runtime.core.entities import Account, Attempt, Challenge, NewAttempt, PageSlice
from control_plane.runtime.core.evaluation_command import EvaluationCommand
from control_plane.runtime.core.lifecycle import LifecycleEvent


class Transaction(Protocol):
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class ChallengeCatalog(Protocol):
    async def get(self, challenge_key: str) -> Challenge | None: ...
    async def page(self, **query: Any) -> PageSlice[Challenge]: ...
    async def increment_accepted(self, challenge_key: str) -> None: ...


class AttemptStore(Protocol):
    async def add(self, item: NewAttempt) -> Attempt: ...
    async def get(self, attempt_key: str) -> Attempt | None: ...
    async def get_by_request_key(self, account_key: uuid.UUID, key: str) -> Attempt | None: ...
    async def page(self, **query: Any) -> PageSlice[Attempt]: ...


class AccountDirectory(Protocol):
    async def get_or_create(self, handle: str) -> Account: ...
    async def find_by_id(self, account_key: str) -> Account | None: ...
    async def find_by_handle(self, handle: str) -> Account | None: ...
    async def record_challenge_completion(self, account_key: uuid.UUID, challenge_key: str) -> bool: ...


class EvaluationOutbox(Protocol):
    async def stage(self, command: EvaluationCommand) -> object: ...


class LifecycleStore(Protocol):
    async def append(self, **event: Any) -> LifecycleEvent: ...
    async def list_for_attempt(self, attempt_key: str) -> list[LifecycleEvent]: ...


class ChallengeRevisionCatalog(Protocol):
    async def latest(self, challenge_key: str) -> Any | None: ...
